# Generated by Django 3.2.5 on 2021-10-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.CharField(max_length=10)),
            ],
        ),
    ]
